// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_500 = "CgkIwf7S_skcEAIQBQ"; // <GPGSID>
        public const string achievement_2000 = "CgkIwf7S_skcEAIQCQ"; // <GPGSID>
        public const string achievement_700 = "CgkIwf7S_skcEAIQBg"; // <GPGSID>
        public const string achievement_100 = "CgkIwf7S_skcEAIQAw"; // <GPGSID>
        public const string leaderboard = "CgkIwf7S_skcEAIQAg"; // <GPGSID>
        public const string achievement_300 = "CgkIwf7S_skcEAIQBA"; // <GPGSID>
        public const string achievement_1000 = "CgkIwf7S_skcEAIQCA"; // <GPGSID>
        public const string achievement_900 = "CgkIwf7S_skcEAIQBw"; // <GPGSID>

}

